export const Colors = {
    white: '#FFF',
    black: '#000',
    background: '#F5F7F9',
    headerShadow: '#E8EAED',
    headerCircleGrayBackground: '#E8E8E8',
    headerCounters: '#0381BE',
    headerInputBorder: '#F1F1F1',
    headerInputColor: '#989BA0',
    profileTextColor: '#4456A9',
    subProfileTextColor: '#B9BBBF',
    profileItemTextColor: '#7A8090',
    workspaceTitleColor: '#303952',
    constantPartContainer: '#858585',
    profilePropertiesBackground: '#E6F0F3',
    profilePropertiesColor: '#60A2B3',
    moreLabelColor: '#6FABBB',
    switchButtonBackgroundColor: '#EAECF5',
    rigidButtonTextColor: '#2A3F9D'
}